// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe5xG4XUUjkOc9Fu31Z9M_Jppab76c-n4',
    appId: '1:371599103359:web:fa2fcbcc7c387845ee364a',
    messagingSenderId: '371599103359',
    projectId: 'rental-app-sharon',
    authDomain: 'rental-app-sharon.firebaseapp.com',
    storageBucket: 'rental-app-sharon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-vfmgyFk8MvScwK-59_aHT3-xGapOfzE',
    appId: '1:371599103359:android:4ad4b055de045fa5ee364a',
    messagingSenderId: '371599103359',
    projectId: 'rental-app-sharon',
    storageBucket: 'rental-app-sharon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5_kg4cIAZ3DaAaIsNHQUej-cITd-oqwo',
    appId: '1:371599103359:ios:b4974c91a12f6012ee364a',
    messagingSenderId: '371599103359',
    projectId: 'rental-app-sharon',
    storageBucket: 'rental-app-sharon.firebasestorage.app',
    iosBundleId: 'com.example.rentalAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5_kg4cIAZ3DaAaIsNHQUej-cITd-oqwo',
    appId: '1:371599103359:ios:b4974c91a12f6012ee364a',
    messagingSenderId: '371599103359',
    projectId: 'rental-app-sharon',
    storageBucket: 'rental-app-sharon.firebasestorage.app',
    iosBundleId: 'com.example.rentalAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe5xG4XUUjkOc9Fu31Z9M_Jppab76c-n4',
    appId: '1:371599103359:web:387f202bcfc5ff32ee364a',
    messagingSenderId: '371599103359',
    projectId: 'rental-app-sharon',
    authDomain: 'rental-app-sharon.firebaseapp.com',
    storageBucket: 'rental-app-sharon.firebasestorage.app',
  );
}
